version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-app
    restart: always
    ports:
      - "3030:3030"
    environment:
      DATABASE_URI: mongodb://mongodb:27017
    depends_on:
        - mongodb