version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  get_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: get_service
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongodb:27017

  post_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post_service
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongodb:27017

  put_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: put_service
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongodb:27017

  delete_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delete_service
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongodb:27017

  render_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render_service
    restart: always
    environment:
      - DATABASE_URI=mongodb://mongodb:27017

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - get_service
      - post_service
      - put_service
      - delete_service
      - render_service
